### ISSUE TITLE
Hurtbox & Hitbox Bugs

### ISSUE THREAD

**Issue by DevLMMK** [brannotaylor/SurvivorsClone_Base#1]
Hey dude! I've been following you along in your Godot tutorials on YouTube! Pretty awesome so far! Keep up the good work. 
However, I have an error with the hit and hurt boxes. Can you take a look?
[SurvivorsClone_Base-main 2.zip](https://github.com/brannotaylor/SurvivorsClone_Base/files/12064830/SurvivorsClone_Base-main.2.zip)

**Comment by DevLMMK** [comment]
Nevermind lol, i fixed it

**Comment by aftrosrs** [comment]
I would like to note that at the point of where people are doing part 4, there are a lot of people mentioning that the hurt/hitbox was wrong in the tutorial(which i ran into some problems myself)

What i've done is make my own repo with everything up to the end of part 4 at https://github.com/aftrosrs/Part_4
hopefully this helps someone in the future.
